# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 22:54
from __future__ import unicode_literals

from django.db import migrations


def forward_course_abc_to_mti(apps, schema_editor):
    """
    Para cada ABC instanciar um MTI com todos os atributos
    Salvar o MIT
    Associar os speaker do abc no mti
    deletar o abc"""

    copy_src_to_dst(apps.get_model('core', 'CourseOld'),#Modelo no instante que a migração foi gerada
                    apps.get_model('core', 'Course')
                    )


def backward_course_abc_to_mti(apps, schema_editor):
    """
    Para cada ABC instanciar um MTI com todos os atributos
    Salvar o MIT
    Associar os speaker do abc no mti
    deletar o abc"""
    copy_src_to_dst(apps.get_model('core', 'CourseOld'),  # Modelo no instante que a migração foi gerada
                    apps.get_model('core', 'Course')
                    )



def copy_src_to_dst(Source, Destination):
    for src in Source.objects.all():
        dst = Destination(title=src.title,
                        start=src.start,
                        description=src.description,
                        slots=src.slots

                    )

        dst.save()
        dst.speakers.set(src.speakers.all())
        src.delete()




class Migration(migrations.Migration):


    dependencies = [
        ('core', '0010_course'),
    ]

    operations = [
        migrations.RunPython(forward_course_abc_to_mti)
    ]
